commitizen:
  bump_message: 'chore(release): release $new_version'
  tag_format: v$version
  version_provider: scm
  update_changelog_on_bump: true
  major_version_zero: true
  changelog_file: CHANGELOG.md
